//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class parameterschoolmap
    {
        public int parameterschoolmapid { get; set; }
        public Nullable<int> parameterid { get; set; }
        public Nullable<int> schoolid { get; set; }
        public string alterparameter { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
    
        public virtual parameter parameter { get; set; }
        public virtual school school { get; set; }
    }
}
