//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentdailyperformance
    {
        public long studentdailyperformanceid { get; set; }
        public Nullable<int> studentschoolmapid { get; set; }
        public Nullable<int> Attendance { get; set; }
        public Nullable<int> Discipline { get; set; }
        public Nullable<int> HomeWork { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> monthid { get; set; }
        public Nullable<int> yearid { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> Points { get; set; }
    
        public virtual studentschoolmap studentschoolmap { get; set; }
    }
}
