//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentteacher
    {
        public int studentteacherid { get; set; }
        public Nullable<int> studentid { get; set; }
        public Nullable<int> teacherid { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual student student { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
