//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentschoolmap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public studentschoolmap()
        {
            this.studentdailyperformances = new HashSet<studentdailyperformance>();
        }
    
        public int studentschoolmapid { get; set; }
        public Nullable<int> studentid { get; set; }
        public Nullable<int> schoolid { get; set; }
        public Nullable<int> classid { get; set; }
        public Nullable<int> divisionid { get; set; }
        public string rollnumber { get; set; }
        public Nullable<int> groupid { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual division division { get; set; }
        public virtual group group { get; set; }
        public virtual school school { get; set; }
        public virtual student student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentdailyperformance> studentdailyperformances { get; set; }
    }
}
